# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 76b27fd0e648e92ee52b51f0d3d05a3b87e12888324f09fd2dfe0a86d6409786dc82d0e8b501b1a0277a990f39b0f597aad703e4c14289949f3a95ea96369ac5

test:
  secret_key_base: a7e26c065904995e35162ba9f196eb20309a8d7267d189734c6a0c8d3eff4e6fc754dbbdd0cf59dd91e00a562e16d4fc786101feb7de1dbc78e37ddde9dbbf0f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
